# Generated by Django 2.2.17 on 2021-12-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='marker_type',
            field=models.CharField(default='road', max_length=100),
            preserve_default=False,
        ),
    ]
