# Generated by Django 2.2.17 on 2021-12-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_marker_marker_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('marker_slug', models.CharField(max_length=300)),
                ('image_path', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=230, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
