# Generated by Django 2.2.17 on 2021-12-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_problemrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemrequest',
            name='image_path',
        ),
        migrations.AddField(
            model_name='problemrequest',
            name='image',
            field=models.ImageField(default='', upload_to='problemrequests'),
            preserve_default=False,
        ),
    ]
