# Generated by Django 2.2.17 on 2021-12-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20211216_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemrequest',
            name='image',
            field=models.FileField(upload_to='problemrequests'),
        ),
    ]
